[package]
name = "aa-bundler"
version = "0.1.0"
authors = ["Vid Kersic <vid.kersic@yahoo.com>"]
edition = "2021"
description = "AA - Bundler implementation"
default-run = "bundler"

[dependencies]
anyhow = "1"
async-trait = "0.1"
clap = { version = "4", features = ["derive"] }
dirs = "4.0"
educe = { version = "0.4", features = ["Debug", "Default"] }
ethereum-interfaces = { git = "https://github.com/ledgerwatch/interfaces" }
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "b27c7b0", features = ["ethers-solc"]  }
expanded-pathbuf = "0.1"
hex = { version = "0.4.3", default-features = false, features = ["std"] }
jsonrpsee = { version = "0.16", features = ["server", "macros"] }
parking_lot = "0.12"
prost = "0.11"
ron = "0.8"
serde = "1"
serde_json = "1"
tokio = { version = "1.18", features = ["full"] }
tonic = { version = "0.8", default-features = false, features = [
    "codegen",
    "prost",
    "transport",
] }
tracing = "0.1"
tracing-subscriber = "0.3"
regex = "1"

[build-dependencies]
anyhow = "1"
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "b27c7b0", features = ["ethers-solc"]  }
protobuf-src = "1.1.0"
prost-build = "0.11"
tonic-build = "0.8"

[[bin]]
path = "bin/bundler.rs"
name = "bundler"

[[bin]]
path = "bin/bundler-uopool.rs"
name = "bundler-uopool"

[[bin]]
path = "bin/bundler-rpc.rs"
name = "bundler-rpc"

[[bin]]
path = "bin/create-wallet.rs"
name = "create-wallet"
