[package]
name = "aa-bundler"
version = "0.1.0"
authors = ["Vid Kersic <vid.kersic@yahoo.com>"]
edition = "2021"
description = "AA - Bundler implementation"
default-run = "bundler"
rust-version = "1.66.1"

[dependencies]
anyhow = "1"
arrayref = "0.3"
async-trait = "0.1"
clap = { version = "4", features = ["derive"] }
dirs = "4.0"
educe = { version = "0.4", features = ["Debug", "Default"] }
ethereum-interfaces = { git = "https://github.com/ledgerwatch/interfaces" }
ethers = { git = "https://github.com/gakonst/ethers-rs.git", rev = "fd83e203b405682cc56cccbac5b43dce33913a8e", features = ["ethers-solc"] }
expanded-pathbuf = "0.1"
hex = { version = "0.4.3", default-features = false, features = ["std"] }
jsonrpsee = { version = "0.16", features = ["server", "macros"] }
page_size = "0.5.0"
parking_lot = "0.12"
prost = "0.11"
regex = "1"
reth-db = { git = "https://github.com/paradigmxyz/reth.git", rev = "314ea0883b1062375ad86577be1fccc39233739d" }
reth-libmdbx = { git = "https://github.com/paradigmxyz/reth.git", rev = "314ea0883b1062375ad86577be1fccc39233739d" }
ron = "0.8"
rustc-hex = "^2.0.1"
serde = "1"
serde_json = "1"
tokio = { version = "1.18", features = ["full"] }
tonic = { version = "0.8", default-features = false, features = [
    "codegen",
    "prost",
    "transport",
] }
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
tempdir = "0.3.7"

[build-dependencies]
anyhow = "1"
ethers = { git = "https://github.com/gakonst/ethers-rs.git", rev = "fd83e203b405682cc56cccbac5b43dce33913a8e", features = ["ethers-solc"] }
prost-build = "0.11"
protobuf-src = "1.1.0"
tonic-build = "0.8"

[[bin]]
path = "bin/bundler.rs"
name = "bundler"

[[bin]]
path = "bin/bundler-uopool.rs"
name = "bundler-uopool"

[[bin]]
path = "bin/bundler-rpc.rs"
name = "bundler-rpc"

[[bin]]
path = "bin/create-wallet.rs"
name = "create-wallet"
