[package]
name = "aa-bundler-primitives"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = """
AA (ERC-4337) Bundler commonly used types
"""

[dependencies]
anyhow = "1"
educe = { version = "0.4", features = ["Debug", "Default"] }
ethers = { workspace = true }
expanded-pathbuf = "0.1"
lazy_static = "1.4.0"
rustc-hex = "^2.0.1"
serde = "1"
serde_json = "1"
strum = "0.24"
strum_macros = "0.24"
tokio = { workspace = true }
tracing = { workspace = true }

[features]
test-utils = []
