version: '2'

services:
  bundler:
    image: ghcr.io/vid201/aa-bundler:latest
    command: --rpc-listen-address 0.0.0.0:3000 --eth-client-address http://geth-dev:8545 --mnemonic-file /root/${BUNDLER_ACCOUNT} --beneficiary 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 --gas-factor 600 --min-balance 1 --entry-points 0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789 --min-stake 1 --min-unstake-delay 0 --min-priority-fee-per-gas 0 --max-verification-gas 1500000 --rpc-api eth,debug
    ports: [ '3000:3000' ]
    volumes:
      - ./keys:/root
    depends_on: [ geth-dev ]
  geth-dev:
    build: geth-dev
    ports: [ '8545:8545' ]